# Generated by Django 4.2.3 on 2023-07-26 11:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="borroving",
            new_name="borrowing",
        ),
    ]
