# Generated by Django 4.2.3 on 2023-07-26 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="borroving",
            new_name="borrowing",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="stripe_sesion_id",
            new_name="stripe_session_id",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="stripe_sesion_url",
            new_name="stripe_session_url",
        ),
    ]
