# Generated by Django 4.2.3 on 2023-07-16 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.CharField(
                choices=[("HARD", "HARD"), ("SOFT", "SOFT")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="inventory",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
