# Generated by Django 4.2.3 on 2023-07-16 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("borrowings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="borrowing",
            old_name="actual_return",
            new_name="actual_return_date",
        ),
        migrations.RenameField(
            model_name="borrowing",
            old_name="extend_return",
            new_name="extend_return_date",
        ),
    ]
