# Generated by Django 4.2.3 on 2023-07-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "borrowings",
            "0002_rename_actual_return_borrowing_actual_return_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="borrow_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
